# system pins
HOLD_VSYS_EN_PIN = 2
I2C_SDA_PIN = 4
I2C_SCL_PIN = 5
WIFI_CS_PIN = 25

# sensor pins
EXTERNAL_INTERRUPT_PIN = 3
ACTIVITY_LED_PIN = 6
BUTTON_PIN = 7
RTC_ALARM_PIN = 8
WIND_SPEED_PIN = 9
RAIN_PIN = 10
WIND_DIR_PIN = 26

# wake reasons
WAKE_UNKNOWN = None
WAKE_BUTTON_PRESS = 2
WAKE_RTC_ALARM = 3
WAKE_EXT_TRIGGER = 4
WAKE_RAIN_TRIGGER = 5
WAKE_USB_POWERED = 6

# warn LED states
WARN_LED_OFF = 0
WARN_LED_ON = 1
WARN_LED_BLINK = 2
